WebApplication1/Controllers/P010Controller.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.VM;

namespace WebApplication1.Controllers
{
    public class P010Controller : Controller
    {
        // GET: P010
        public ActionResult A01()
        {
            return View();
        }
        [HttpPost]
		public ActionResult A01(P010A01VM model)
        {
            if(model.File== null||string.IsNullOrEmpty(model.File.FileName)||model.File.ContentLength==0) {
                model.FileName=string.Empty;
            }
            else
            {
                string path = Server.MapPath("/Uploads");
                string fileName=System.IO.Path.GetFileName(model.File.FileName);
                string newFileName=GetNewFileName(path,fileName);
                string fullPath=System.IO.Path.Combine(path, newFileName);
                try
                {
                    model.File.SaveAs(fullPath);
                    model.FileName= newFileName;
                    return View();
                }catch(Exception ex)
                {
                    ModelState.AddModelError(string.Empty,"上傳檔案失敗"+ex.Message);
                }

            }

            return RedirectToAction("index","Home");
        }
        private string GetNewFileName(string path, string fileName)
        {
            string ext=System.IO.Path.GetExtension(fileName);
            string newFileName=string.Empty;
            string fullPath=string.Empty;
            do
            {
                newFileName = Guid.NewGuid().ToString("N") + ext;
                fullPath = System.IO.Path.Combine(path, newFileName);

            } while (System.IO.File.Exists(fullPath) == true);
            return newFileName;
        }

	}
}

WebApplication1/Views/P010/A01.cshtml
@model WebApplication1.Models.VM.P010A01VM

@{
    ViewBag.Title = "A01";
}

<h2>A01</h2>

@using (Html.BeginForm("A01", "P010", FormMethod.Post, new {enctype="multipart/form-data"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>P010A01VM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="File" class="form-control"/>
                @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>